<a href="https://colab.research.google.com/github/informmuthukumar/test/blob/master/hackearth_diabetesMed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries**

In [161]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

**Importing the Dataset**

In [162]:
train = pd.read_csv('train.csv')
#test = pd.read_csv('test.csv')

In [163]:
print(train.shape)
#print(test.shape)

(14696, 50)


In [164]:
features_list=['encounter_id', 'patient_id', 'race', 'gender', 'age', 'admission_type_id', 'discharge_disposition_id',
                  'admission_source_id', 'time_in_hospital', 'tel_1', 'tel_3', 'tel_4', 'tel_5', 'tel_6', 'tel_7',
                  'tel_8', 'tel_9', 'tel_10', 'tel_11', 'tel_12', 'tel_13', 'tel_14', 'tel_15', 'tel_18', 'tel_43', 
                  'tel_48', 'tel_49']

In [165]:
X = train.loc[:, features_list]
y = train.iloc[:, -1]               

In [166]:
print(X)

       encounter_id  patient_id             race  ...  tel_43 tel_48  tel_49
0         178974720    61754247        Caucasian  ...      No     Ch     >30
1         111231666   110498427  AfricanAmerican  ...  Steady     No      NO
2         134751624    91719990        Caucasian  ...      No     Ch     >30
3         254196636     1897758        Caucasian  ...      No     Ch     >30
4         432617750    34636617            Asian  ...      No     No      NO
...             ...         ...              ...  ...     ...    ...     ...
14691     166648812    91484838        Caucasian  ...      No     Ch     >30
14692     196987788    78710643        Caucasian  ...      No     No     >30
14693     271832286    32262471        Caucasian  ...      No     No      NO
14694     254610744    96558903  AfricanAmerican  ...      No     Ch      NO
14695     169334802    23238954  AfricanAmerican  ...      No     Ch      NO

[14696 rows x 27 columns]


In [167]:
print(y)

0        1
1        1
2        1
3        1
4        1
        ..
14691    1
14692    1
14693    0
14694    1
14695    1
Name: diabetesMed, Length: 14696, dtype: int64


In [168]:
X = X.replace(to_replace='?',value=np.nan)

In [169]:
type(X)

pandas.core.frame.DataFrame

In [170]:
cat_cols=list(X.select_dtypes(include=['object']).columns)
num_cols=list(X.select_dtypes(exclude=['object']).columns)

In [202]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X)
X_df = imputer.transform(X)

In [203]:
print(X_df)

[[178974720 61754247 'Caucasian' ... 'No' 'Ch' '>30']
 [111231666 110498427 'AfricanAmerican' ... 'Steady' 'No' 'NO']
 [134751624 91719990 'Caucasian' ... 'No' 'Ch' '>30']
 ...
 [271832286 32262471 'Caucasian' ... 'No' 'No' 'NO']
 [254610744 96558903 'AfricanAmerican' ... 'No' 'Ch' 'NO']
 [169334802 23238954 'AfricanAmerican' ... 'No' 'Ch' 'NO']]


In [ ]:
#numpy_data = np.array([[1, 2], [3, 4]])


In [180]:
X[num_cols]

encounter_id  patient_id  admission_type_id  ...  tel_7  tel_8  tel_12
0         178974720    61754247                  1  ...      0      0       5
1         111231666   110498427                  3  ...      0      0       4
2         134751624    91719990                  1  ...      0      1       9
3         254196636     1897758                  3  ...      0      0       7
4         432617750    34636617                  2  ...      0      0       9
...             ...         ...                ...  ...    ...    ...     ...
14691     166648812    91484838                  1  ...      0      1       8
14692     196987788    78710643                  1  ...      0      2       9
14693     271832286    32262471                  1  ...      0      0       9
14694     254610744    96558903                  1  ...      0      0       5
14695     169334802    23238954                  1  ...      0      0       8

[14696 rows x 13 columns]

In [237]:
type(X_df)
X_df_pd=pd.DataFrame(X_df,columns=features_list)

In [248]:
from sklearn.preprocessing import LabelEncoder
data1 = X_df_pd[cat_cols].apply(LabelEncoder().fit_transform)


In [251]:
dataf=data1.join(X_df_pd[num_cols])

In [253]:
dataf.head()

race  gender  age  tel_1  tel_9  tel_10  ...  tel_4  tel_5  tel_6  tel_7  tel_8  tel_12
0     2       1    8      6    398      90  ...      0      8      0      0      0       5
1     0       0    5      0    385     376  ...      1     16      0      0      0       4
2     2       1    8      6    246     490  ...      2     15      0      0      1       9
3     2       0    7      6    375      45  ...      2     24      0      0      0       7
4     1       0    8      6    402     381  ...      2     11      0      0      0       9

[5 rows x 27 columns]

In [255]:
X_final=dataf.values
y_final=y.values

In [265]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.2, random_state = 1)

In [262]:
y.value_counts()

1    13207
0     1489
Name: diabetesMed, dtype: int64

In [266]:
print(X_train)

[[2 0 6 ... 0 0 8]
 [2 1 6 ... 0 0 7]
 [4 1 8 ... 0 0 9]
 ...
 [2 1 6 ... 0 1 7]
 [2 0 7 ... 0 0 9]
 [2 0 3 ... 6 0 9]]


In [268]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [270]:
print(X_train)

[[ 0.37019092 -0.9285414  -0.10920275 ... -0.27212356 -0.51320735
   0.14225061]
 [ 0.37019092  1.0769579  -0.10920275 ... -0.27212356 -0.51320735
  -0.40802848]
 [ 2.77924956  1.0769579   1.17266203 ... -0.27212356 -0.51320735
   0.6925297 ]
 ...
 [ 0.37019092  1.0769579  -0.10920275 ... -0.27212356  0.27452808
  -0.40802848]
 [ 0.37019092 -0.9285414   0.53172964 ... -0.27212356 -0.51320735
   0.6925297 ]
 [ 0.37019092 -0.9285414  -2.03199994 ...  6.14744412 -0.51320735
   0.6925297 ]]


In [271]:
print(X_test)

[[ 0.37019092 -0.9285414  -0.75013515 ...  0.79780439 -0.51320735
   0.6925297 ]
 [ 0.37019092  1.0769579  -0.75013515 ... -0.27212356 -0.51320735
  -0.95830757]
 [ 0.37019092  1.0769579  -0.75013515 ... -0.27212356 -0.51320735
   0.6925297 ]
 ...
 [ 0.37019092  1.0769579  -0.10920275 ... -0.27212356 -0.51320735
   0.6925297 ]
 [-2.03886772  1.0769579  -2.03199994 ...  1.86773233  1.84999893
   0.6925297 ]
 [-2.03886772 -0.9285414   0.53172964 ... -0.27212356 -0.51320735
   0.6925297 ]]


In [272]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [273]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [274]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  88  218]
 [  77 2557]]


0.8996598639455783

In [240]:
X_df_pd.head()

encounter_id patient_id             race  gender  ... tel_18  tel_43 tel_48 tel_49
0    178974720   61754247        Caucasian    Male  ...     No      No     Ch    >30
1    111231666  110498427  AfricanAmerican  Female  ...     No  Steady     No     NO
2    134751624   91719990        Caucasian    Male  ...     No      No     Ch    >30
3    254196636    1897758        Caucasian  Female  ...     No      No     Ch    >30
4    432617750   34636617            Asian  Female  ...     No      No     No     NO

[5 rows x 27 columns]

In [244]:
column_idx=X_df_pd.columns
print(column_idx)
X_df_pd[[cat_cols]]

Index(['encounter_id', 'patient_id', 'race', 'gender', 'age',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'tel_1', 'tel_3', 'tel_4', 'tel_5', 'tel_6',
       'tel_7', 'tel_8', 'tel_9', 'tel_10', 'tel_11', 'tel_12', 'tel_13',
       'tel_14', 'tel_15', 'tel_18', 'tel_43', 'tel_48', 'tel_49'],
      dtype='object')


KeyError: ignored

In [191]:
from sklearn.preprocessing import LabelEncoder
data1 = X_df['race'].apply(LabelEncoder().fit_transform)

IndexError: ignored

In [ ]:
pd.get_dummies(X_df_pd,columns=X_df_pd

In [245]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[2,3])], remainder='passthrough')
X_df_one = np.array(ct.fit_transform(X_df))

In [247]:
print(X_df)
print(X_df_one)
X_df_one.shape

[[178974720 61754247 'Caucasian' ... 'No' 'Ch' '>30']
 [111231666 110498427 'AfricanAmerican' ... 'Steady' 'No' 'NO']
 [134751624 91719990 'Caucasian' ... 'No' 'Ch' '>30']
 ...
 [271832286 32262471 'Caucasian' ... 'No' 'No' 'NO']
 [254610744 96558903 'AfricanAmerican' ... 'No' 'Ch' 'NO']
 [169334802 23238954 'AfricanAmerican' ... 'No' 'Ch' 'NO']]
[[0.0 0.0 1.0 ... 'No' 'Ch' '>30']
 [1.0 0.0 0.0 ... 'Steady' 'No' 'NO']
 [0.0 0.0 1.0 ... 'No' 'Ch' '>30']
 ...
 [0.0 0.0 1.0 ... 'No' 'No' 'NO']
 [1.0 0.0 0.0 ... 'No' 'Ch' 'NO']
 [1.0 0.0 0.0 ... 'No' 'Ch' 'NO']]


(14696, 32)

In [250]:
type(data1)
data1.head()

race  gender  age  tel_1  tel_9  ...  tel_15  tel_18  tel_43  tel_48  tel_49
0     2       1    8      6    398  ...       1       0       0       0       1
1     0       0    5      0    385  ...       1       0       1       1       2
2     2       1    8      6    246  ...       1       0       0       0       1
3     2       0    7      6    375  ...       1       0       0       0       1
4     1       0    8      6    402  ...       1       0       0       1       2

[5 rows x 14 columns]

In [ ]:
X.isnull().sum(axis=0).head(30)

**Removing the columns which has one distinct value** After combining both training and test data

In [31]:
traintest=pd.concat([train,test],axis=0)

In [32]:
feats_counts=train.nunique(dropna=False)


In [46]:
feats_counts.sort_values()[:10]

tel_28         1
tel_47         1
tel_20         1
tel_45         1
tel_29         1
tel_30         1
tel_41         1
tel_18         2
tel_23         2
diabetesMed    2
dtype: int64

In [68]:
constant_features=feats_counts.loc[feats_counts==1].index.tolist()
print(constant_features)




['tel_20', 'tel_28', 'tel_29', 'tel_30', 'tel_41', 'tel_45', 'tel_47']


In [72]:
cat_cols=list(train.select_dtypes(include=['object']).columns)
num_cols=list(train.select_dtypes(exclude=['object']).columns)

In [73]:
cat_cols

['race',
 'gender',
 'age',
 'weight',
 'tel_1',
 'tel_2',
 'tel_9',
 'tel_10',
 'tel_11',
 'tel_13',
 'tel_14',
 'tel_15',
 'tel_16',
 'tel_17',
 'tel_18',
 'tel_19',
 'tel_20',
 'tel_21',
 'tel_22',
 'tel_23',
 'tel_24',
 'tel_25',
 'tel_26',
 'tel_27',
 'tel_28',
 'tel_29',
 'tel_30',
 'tel_41',
 'tel_42',
 'tel_43',
 'tel_44',
 'tel_45',
 'tel_46',
 'tel_47',
 'tel_48',
 'tel_49']

In [74]:
num_cols

['encounter_id',
 'patient_id',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'tel_3',
 'tel_4',
 'tel_5',
 'tel_6',
 'tel_7',
 'tel_8',
 'tel_12',
 'diabetesMed']

In [ ]:
traintest.drop(constant_features,axis=1,inplace=True)


In [70]:
nunique=train.nunique(axis=0,dropna=False)
nunique

encounter_id                14696
patient_id                  13011
race                            6
gender                          2
age                            10
weight                          9
admission_type_id               8
discharge_disposition_id       20
admission_source_id            16
time_in_hospital               14
tel_1                          17
tel_2                          48
tel_3                         104
tel_4                           7
tel_5                          70
tel_6                          26
tel_7                          22
tel_8                          16
tel_9                         512
tel_10                        505
tel_11                        537
tel_12                         16
tel_13                          4
tel_14                          4
tel_15                          4
tel_16                          4
tel_17                          4
tel_18                          2
tel_19                          4
tel_20        

In [45]:
#train[train['weight']=='?']
train_None= train.replace(to_replace='?',value=np.nan)
train_None.isnull().sum(axis=0).head(51)
#train_None.head(10)

encounter_id                    0
patient_id                      0
race                          337
gender                          0
age                             0
weight                      14315
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
tel_1                        2458
tel_2                        8122
tel_3                           0
tel_4                           0
tel_5                           0
tel_6                           0
tel_7                           0
tel_8                           0
tel_9                           1
tel_10                         33
tel_11                        139
tel_12                          0
tel_13                          0
tel_14                          0
tel_15                          0
tel_16                          0
tel_17                          0
tel_18                          0
tel_19                          0
tel_20        

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X = sc.fit_transform(X)
Y = sc.transform(Y)